version: "3.3"
services:
  be:
    build:
      context: .
      dockerfile: 'Dockerfile'

    depends_on:
      - "db"
    restart: always
    env_file:
      - .env
    networks:
      - app-network
    ports:
      - '80:1337'
    volumes:
      - /usr/app/node_modules

  db:
    container_name: smart-health_db
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: smart-health
    ports:
      - '3406:3306'
    networks:
      - app-network
    volumes:
      - mysql_db:/var/lib/mysql/data

volumes:
  mysql_db:
    external: false
      
networks:
  app-network:
    driver: bridge